OPENSTACK-2522: enable driver to update port mac
F5Networks/f5-openstack-lbaasv2-driver pull request #1147
Opened 2022-08-16 09:12 UTC by zhang-shengping

2022-08-18 01:35 UTC, zhaoqin-github requested changes

2022-08-18 01:35 UTC, zhaoqin-github commented on f5lbaasdriver/v2/bigip/plugin_rpc.py
> +        if not port['port']:
Does it really happen?

2022-08-24 07:49 UTC, zhang-shengping commented on f5lbaasdriver/v2/bigip/plugin_rpc.py
> +        if not port['port']:
> Does it really happen?

nothing will be update, and return None

2022-08-25 03:13 UTC, zhaoqin-github approved these changes

2022-08-26 08:13 UTC, merged